create table amount_units
(
    id    integer generated always as identity
        constraint amount_units_pk
            primary key,
    title text
);

create table types
(
    id    integer generated always as identity
        constraint type_form_pk
            primary key,
    title text not null
);

create table medicines
(
    id             integer generated by default as identity
        constraint medicines_pk
            primary key,
    title          text not null,
    amount         integer,
    type_id        integer
        constraint type_fk
            references types,
    amount_unit_id integer
        constraint amount_unit_fk
            references amount_units
);

INSERT INTO public.types (title) VALUES ('Таблетки');
INSERT INTO public.types (title) VALUES ('Капсулы');
INSERT INTO public.types (title) VALUES ('Раствор для инъекций');
INSERT INTO public.types (title) VALUES ('Мазь');
INSERT INTO public.types (title) VALUES ('Гель');
INSERT INTO public.types (title) VALUES ('Раствор');
INSERT INTO public.types (title) VALUES ('Капли');
INSERT INTO public.types (title) VALUES ('Прочее');


INSERT INTO public.amount_units (title) VALUES ('шт');
INSERT INTO public.amount_units (title) VALUES ('г');
INSERT INTO public.amount_units (title) VALUES ('мг');
INSERT INTO public.amount_units (title) VALUES ('мкг');
INSERT INTO public.amount_units (title) VALUES ('л');
INSERT INTO public.amount_units (title) VALUES ('мл');
INSERT INTO public.amount_units (title) VALUES ('мкл');


INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (1, 'Анальгин 500 мг', 20, 1, 1);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (2, 'Лоперамид 2мг', 10, 2, 1);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (3, 'Кетонал 50 мг/мл', 5, 3, 1);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (4, 'Гидрокортизон 1%', 10, 4, 2);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (5, 'Вольтарен 2%', 100, 5, 2);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (6, 'Рингера', 400, 6, 6);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (7, 'Отривин 0.1%', 10, 7, 6);
INSERT INTO public.medicines (id, title, amount, type_id, amount_unit_id) VALUES (8, 'Бинт стерильный 10 см', 1, 8, 1);
