server:
  port: 9000
  servlet:
    context-path: /
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/home_pharmacy
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
